version: '3'

services:
  traefik:
    image: traefik:1.5
    command: --web --web.metrics.prometheus --web.metrics.prometheus.buckets="0.1,0.3,1.2,5.0" --docker
    restart: always
    ports:
      - 80:80
      - 443:443
      - 10002:8080
      - 10001:8082
      - 10000:8081
    labels:
      - "traefik.frontend.rule=Host:docker.lbr.lu"
      - "traefik.frontend.entryPoints=http-admin"
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/traefik/traefik.toml:/etc/traefik/traefik.toml
      - /opt/traefik/acme.json:/etc/traefik/acme.json

  portainer:
    image: portainer/portainer
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainerdata:/data"
    networks:
      - web
    
    labels:
      - "traefik.enable=true"
      - "traefik.port=9000"
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:portainer.lbr.lu"

  redis-rcsl:

    restart: always
    image: redis:latest
    expose:
      - "6379"
    networks:
      - web
  
    volumes:
    - ./redis:/data

   
  
  rocketchat:
   

    image: rocketchat/rocket.chat

    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.port=3000"
      - "traefik.frontend.rule=Host:chat.lbr.lu"
      - "traefik.frontend.entryPoints=http"
    environment:
      - MAIL_URL=${MAIL_URL}
      - MONGO_URL=${MONGO_URL}
      - ROOT_URL=${ROOT_URL}
      - Accounts_UseDNSDomainCheck=${Accounts_UseDNSDomainCheck}
    depends_on:
      - mongodb
    ports:
      - 3100:3100
  
    networks:
      - web

  mongodb:
    image: mongo
    hostname: 'mongodb'
    volumes:
     - ./db/data:/data/db
     - ./db/dump:/dump
    command: mongod --smallfiles
    networks:
      - web

  hubot:
    build: ./hubot 
    hostname: "hubot"
    environment:
      - ROCKETCHAT_URL=${ROCKETCHAT_URL}
      - ROCKETCHAT_ROOM=${ROCKETCHAT_ROOM}
      - ROCKETCHAT_USER=${ROCKETCHAT_USER}
      - ROCKETCHAT_PASSWORD=${ROCKETCHAT_PASSWORD}
      - ROCKETCHAT_AUTH=${ROCKETCHAT_AUTH}
      - BOT_NAME=${BOT_NAME}
      - LISTEN_ON_ALL_PUBLIC=${LISTEN_ON_ALL_PUBLIC}
      - EXTERNAL_SCRIPTS=${EXTERNAL_SCRIPTS}

    volumes:
      - ./hubot/scripts:/home/hubot/scripts
      - ./hubot/pythonscripts:/myhubot/pythonscripts
    depends_on:
      - rocketchat
    networks:
      - web


  wiki:
    # Use an already built XWiki image from DockerHub.
    #image: "xwiki:9.11.3-postgres-tomcat"
    image: "xwiki:10.4-postgres-tomcat"
    depends_on:
      - xwiki-postgres-db
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_HOST=${DB_HOST}

    # The DB_USER/DB_PASSWORD/DB_HOST variables are used in the hibernate.cfg.xml file.

    # Provide a name instead of an auto-generated id for the xwiki permanent directory configured in the Dockerfile,
    # to make it simpler to identify in 'docker volume ls'.
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:wiki.lbr.lu"
      - "traefik.frontend.entryPoints=http"
    ports:
      - 8080:8080
    volumes:
      - xwiki-data:/usr/local/xwiki
    networks:
      - web

  # The container that runs PostgreSQL
  xwiki-postgres-db:
    image: "postgres:9.5"
    environment:
      - POSTGRES_ROOT_PASSWORD=${POSTGRES_ROOT_PASSWORD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_INITDB_ARGS=${POSTGRES_INITDB_ARGS}


    volumes:
      - postgres-data:/var/lib/postgresql/data

    networks:
      - web
      
  pdferrors-django:
    build: ./pdflist
    expose:
     - "8888"
    ports:
      - 8888:8888
    command: sh -c 'python3 manage.py makemigrations && python3 manage.py migrate --run-syncdb && python3 createsuperuser.py && python3 eventmanager.py & gunicorn mydjango.wsgi:application -w 2 -b :8888'
    working_dir: /data/pdflist/mydjango
    environment:
      - CREATE_SUPER_USER=${CREATE_SUPER_USER}
      - SUPER_USER=${SUPER_USER}
      - SUPER_USER_PASSWORD=${SUPER_USER_PASSWORD}
      - SUPER_USER_EMAIL=${SUPER_USER_EMAIL}
      - DB_NAME=${PDFERROR_DB_NAME}
      - DB_USER=${PDFERROR_DB_USER}
      - DB_PASS=${PDFERROR_DB_PASS}
      - DB_SERVICE=${PDFERROR_DB_SERVICE}
      - DB_PORT=${PDFERROR_DB_PORT}
    volumes:
      - ./pdflist:/data/pdflist
    
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.port=8888"
      - "traefik.frontend.rule=Host:pdf.lbr.lu"
      - "traefik.frontend.entryPoints=http"
    depends_on:
      - postgres-pdf
    networks:
      - web
    restart: always


  postgres-pdf:
    restart: always
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${PDFERROR_DB_NAME}
      - POSTGRES_USER=${PDFERROR_DB_USER}
      - POSTGRES_PASSWORD=${PDFERROR_DB_PASS}
    labels:
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:pdfdb.lbr.lu"
      - "traefik.enable=true"
      - "traefik.port=5432"
      - "traefik.frontend.entryPoints=http"
    networks:
      - web

    volumes:
      - pdferrordb:/var/lib/postgresql/data
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    expose:
      - "5432"

  poll-errors-intranet:
    build: ./pdferror
    restart: always
    environment:
      - IAM_USER=${IAM_USER}
      - IAM_PASSWORD=${IAM_PASSWORD}
      - FLASK_REDIS_HOST=redis
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.port=5000"  
    networks:
      - web

  pdf-convert:
    restart: always
    build: ./pdfconvert
    volumes:
     - './pdfconvert:/usr/src/app'
     - '/media/docs:/media/docs/'
    environment:
     - PDFPATHORIGIN=${PDFPATHORIGIN}
    networks:
      - web

  websocket-redisbridge:
    build: ./websocket-redisbridge/
    labels:
        - "traefik.backend=uploadws"
        - "traefik.docker.network=web"
        - "traefik.enable=true"
        - "traefik.port=3001"
        - "traefik.frontend.rule=Host:uploadws.lbr.lu"
        - "traefik.frontend.entryPoints=http"
    expose:
      - "3001"
    
    networks:
      - web
    working_dir : /usr/src/app
    command: sh -c 'node ./src/server.js'

  fileuploadservice:
    environment:
      - DESTINATION=/data
    build: ./fileupload/
    labels:
        - "traefik.backend=uploadpdf"
        - "traefik.docker.network=web"
        - "traefik.enable=true"
        - "traefik.port=8080"
        - "traefik.frontend.rule=Host:uploadpdf.lbr.lu"
        - "traefik.frontend.entryPoints=http"
    expose:
      - "8080"
    volumes:
      - '/media/docs:/data'
    networks:
      - web
    working_dir : /usr/src/app
    command: sh -c 'node ./src/index.js'

  fileuploadweb:
    build: ./webuploadpdf/
    labels:
        - "traefik.backend=uploadweb"
        - "traefik.docker.network=web"
        - "traefik.enable=true"
        - "traefik.port=8080"
        - "traefik.frontend.rule=Host:convertpdf.lbr.lu"
        - "traefik.frontend.entryPoints=http"
    expose:
      - "8080"
    networks:
      - web
      
    links:
      - fileuploadservice


networks:
  web:
    external: true

volumes:
  pdferrordb : {}
  aidata: {}
  portainerdata: {}
  mongodb: {}
  postgres-data: {}
  xwiki-data: {}
  
